version: '3.4'

services:
  heisln.user.service:
    image: ${DOCKER_REGISTRY-}heisln-userservice
    container_name: heisln-userservice
    build:
      context: .
      dockerfile: Heisln.Car.Api/Dockerfile
    ports:
      - "9001:80"
    networks:
      - heisln-net
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - heisln-net

networks:
  heisln-net:
    external: true

